---
title: "Overview"
format:
  html:
    page-layout: full
---

## **Introduction**
L2S is a Python library for interacting with the ISN CRI project hosted at SDSC. This project aims to make massive scale simulations of spiking neural networks easily accessible to the research community, and in particular researches interested in neuromorphic computing for artificial intelligence and neuroscience researchers. This library allows a user to define a spiking neural network and execute it on one of two backends: the CRI neuromorphic hardware or if the hardware is not available a python simulation of the hardware.
  
Check out the [Usage](#usage) section for further information, including how to install the project.

## **Installation**

### **Simple Installation**

```bash
$ pip install l2s
```
    
### **Development Installation**

- First install [Poetry](https://python-poetry.org/)
  - If Poetry installs in may be necessary to install an alternative Python distribution such as [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html)
- Then clone this repository: 

```bash
$ git clone https://github.com/Integrated-Systems-Neuroengineering/L2S.git'
```

- Next you will need to clone the cri-simulations repository into the same directory you just cloned this repository into:

```bash
$ git clone https://github.com/Integrated-Systems-Neuroengineering/CRI_Simulations_Public.git'
```

- cd into the L2S repo you cloned and install the needed dependencies. Resolving dependencies may take a while.

```bash
$ cd L2S 
$ poetry install
```

   - Some Python dependencies may require a compiler supporting C++11 to be installed on your system, such as a recent version of GCC

- finally activate the development environment

```bash
$ poetry shell
```
