---
title: "Overview"
format:
  html:
    page-layout: full
---

## **Introduction**
***hs_api*** is a python library for interacting with the ISN CRI project hosted at SDSC. This project aims to make massive scale simulations of spiking neural networks easily accessible to the research community, and in particular researchers interested in neuromorphic computing for artificial intelligence and neuroscience. This library allows a user to define a spiking neural network and execute it on one of two backends:
   
  - the CRI neuromorphic hardware or
  - a python simulation of the hardware
  
Check out the [Usage](/menu/api/usage.qmd) section for further information.

## **Installation**

### **Simple Installation**

```bash
$ pip install hs_api
```
    
### **Development Installation**

- First install [Poetry](https://python-poetry.org/)
  - If Poetry doesn't install it may be necessary to install an alternative Python distribution such as [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html)

- Clone the following dependencies and the `hs_api` repo: 
```bash
# Dependencies
$ git clone https://github.com/Integrated-Systems-Neuroengineering/connectome_utils.git
$ git clone  https://github.com/Integrated-Systems-Neuroengineering/hs_bridge.git

# API repo
$ git clone https://github.com/Integrated-Systems-Neuroengineering/hs_api.git
```

- cd into the hs_api repo you cloned and install the needed dependencies. Resolving dependencies may take a while.

```bash
$ cd hs_api
$ poetry install
```

- Finally activate the development environment

```bash
$ poetry shell
```
