---
title: "Overview"
format:
  html:
    page-layout: full
---

## **Introduction**
---
L2S is a Python library for interacting with the ISN CRI project hosted at SDSC. This project aims to make massive scale simulations of spiking neural networks easily accessible to the research community, and in particular researches interested in neuromorphic computing for artificial intelligence and neuroscience researchers. This library allows a user to define a spiking neural network and execute it on one of two backends: the CRI neuromorphic hardware or if the hardware is not available a python simulation of the hardware.
  
  Check out the Usage section for further information, including how to install the project.

## **Installation**
---
### **Simple Installation**

```bash
$ pip install l2s
```
    
### **Development Installation**

- First install [Poetry](https://python-poetry.org/)
  - If Poetry installs in may be necessary to install an alternative Python distribution such as [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html)
- Then clone this repository: 

```bash
$ git clone https://github.com/Integrated-Systems-Neuroengineering/L2S.git'
```

- Next you will need to clone the cri-simulations repository into the same directory you just cloned this repository into:

```bash
$ git clone https://github.com/Integrated-Systems-Neuroengineering/CRI_Simulations_Public.git'
```

- cd into the L2S repo you cloned and install the needed dependencies. Resolving dependencies may take a while.

```bash
$ cd L2S 
$ poetry install
```

   - Some Python dependencies may require a compiler supporting C++11 to be installed on your system, such as a recent version of GCC

- finally activate the development environment

```bash
$ poetry shell
```
    
**Usage**
---
### **Running on the Simulator**

On your local machine you can run networks using the Python based simulator of the CRI hardware.

### **Defining a Network**
Users are expected to provide three data structures in order to define a network

#### **Defining the Configuration Dictionary**

The configuration dictionary specifies a few properties that are shared by every neuron in the network

- neuron_type specifies the type of neuron model used to calculate membrane potentials
- global_neuron_params is a sub-dictionary of the configuration dictionary
  - v_thr is an entry in the global_neuron_params dictionary, it sets the membrane potential threshold for all neurons in the network

```python
configuration = {}
configuration[neuron_type'] = I&F
configuration['global_neuron_params'] = {}
configuration['global_neuron_params']['v_thr'] = 4
```

- Defining the Axons Dictionary

    The axons dictionary configures inputs to the network. Axons are synapses connected to neurons in the network that the user can manually send spikes over at a given timestep. Each key in the dictionary is the name of an axon. Each value is a list of two element tuples. Each tuple defines an in-going synapse to a neuron. The first element is the name of a neuron in the network and the second element is the weight of the synaptic connection. Synapse weights must be integers, but they may be positive or negative.

```python
axons = {'alpha': [('a', 3)], 'beta': [('d', 3)]}
```

- Defining the Connections Dictionary: 
    
    The connections dictionary defines the neurons in the network and the connections between them. Each key in the dictionary is the name of a neuron. Of note the names of neurons in the connections dictionary and the names of axons in the axons dictionary must be mutually exclusive. Each value is a list of two element tuples. Each tuple defines a synapse between neurons in the network. The first element is the name of the postsynaptic neuron and the the second element is the weight of the synapse. Synapse weights must be integers but they may be positive or negative. If a neuron has no outgoing synapses it’s synapse list may be left empty.

```python
connections = {'a': [('b', 1)], 'b': [], 'c': [], 'd': [('c', 1)]}
```

- Defining the Outputs List: 
  
    The outputs list defines the neurons in the network the user wishes to receive spikes from. Each element in the list is the key of a neuron in the connections dictionary.

```python
outputs = ['a', 'b']
```

#### **Initializing a network**
Once we’ve defined the above dictionaries and list we must pass them to the CRI_network constructor to create a CRI_network object.

```python
network = CRI_network(axons=axons,connections=connections,config=config, outputs=outputs)
```


#### **Running a Timestep**
Once we’ve constructed an CRI_network object we can run a timestep. We do so by calling the step() method of CRI_network. This method expects a single input called inputs. Inputs defines the inputs to the network at the current timestep, in particular it is a list of names of axons that you wish to carry spikes into the network at the current timestep. Normally network.step() returns a list of the keys that correspond to neurons that spiked during the given timestep, however the membranePotential parameter can be set to True to additionally output the membranePotentials for all neurons in the network.

```python
inputs = ['alpha','beta']
spikes = network.step(inputs)

#Alternative
potentials, spikes = network.step(inputs, membranePotential=True)
```

This method will return a list of membrane potentials for all neurons in the network after the current timestep has elapsed.

#### **Updating Synapse Weights**
Once the CRI_network class the topology of the network is fixed, that is what axon and neurons are in the network and how they are connected via synapses may not be changed. However it is possible to update the weight of preexisting synapses in the network. This can be done by calling the write_synapse() method of CRI_network. write_synapse() takes three arguments, the presynaptic neuron name, the postsynaptic neuron name, and the new synapse weight.

```python
network.write_synapse('a', 'b', 2)
```