on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          git clone https://github.com/Integrated-Systems-Neuroengineering/connectome_utils.git
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/Integrated-Systems-Neuroengineering/hs_bridge.git
          git clone https://github.com/Integrated-Systems-Neuroengineering/hs_api.git
          cd hs_api
          pip install -e .
          cd ..
          pip list | grep hs_api

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: build docs
        run: |
          make docs

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
